/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {}, 
    colors: {
      // 'text': '#eafbef',
      // 'background': '#030d06',
      // 'primary': '#2ac05f',
      // 'secondary': '#197668',
      // 'accent': '#1f938f',
      'text': '#feeed9',
      'background': '#130a00',
      'primary': '#fcc575',
      'secondary': '#04a47d',
      'accent': '#2b91fa',
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
 
}